server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "http://localhost:3000"
                allowedMethods: "*"
                allowedHeaders: "*"
          routes:
            # Route 1: Auth Service Traffic
            - id: auth-service
              uri: http://localhost:8080
              predicates:
                - Path=/auth/**

           # Route 2: Restaurant Service Traffic
            - id: restaurant-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/restaurants, /api/restaurants/**, /api/menu-items, /api/menu-items/**